server:
  port: 9090
  servlet:
    context-path: /


# shiro
shiro:
  user:
    #登录地址
    loginUrl: /login
    #权限认证失败地址
    unauthorizedUrl: /unauth
    #首页开关地址
    indexUrl: /index
    #验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
mybatis:
  #搜索指定包别名
  type-aliases-package: com.example.popular.domain
  #配置mapper的扫描，找到所有mapper.xml映射文件
  mapper-locations: classpath*:mapper/*Mapper.xml
  #加载全局配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 日志配置
logging:
  level:
    com.example: debug
    org.springframework: warn





spring:
  #文件上传配置
  servlet:
    multipart:
      #单个文件最大值
      max-file-size: 2MB
      #上传文件总的最大值
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
    #热部署开关
  #数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      #初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
#  aop:
#    proxy-target-class: true

